

services:
  database:
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Teste123@"
    volumes:
      - livros-api:/var/opt/mssql
    networks:
      app-network:
        aliases:
          - sql

  dotnet-backend:
    build:
      context: ./Back/Crud/Crud
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - "7026:8080"
    depends_on:
      - database
    networks:
      - app-network

  angular-app:
    build:
      context: ./Front/Teste
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    networks:
      - app-network
    depends_on:
      - dotnet-backend

volumes:
  livros-api:

networks:
  app-network:
    driver: bridge
